#!/system/zbin/bash 
echo -e "\e[93;1;3mWelcome To SaveOurSoul\n\e[0m"
echo -e "\e[96;3;1m"
cat << "EOT"
"SaveOurSoul(sos), This is going to be the last release by GhostXOfficial Team.
SOS is a Tool for Androidx86, which help's to improve system stability and much more.
Pervious version of sos were used in PhoenixOS Spectre and PrimeOS Ghost..! 

Hopefully to bring better Compatibility and User experience...!

Features:- 
1] Sos (save our soul):- It's a Masterscript based on bash shell to bring useful functionalities and some tweaks.
2] Extreme Mode:- To Fake Gpu For Games to unlock inaccessible Graphics settings and Tweak as the user needs (Based on Gltoools)
3] ScreenRecoder(CLI):- To Record Screen in sos (Game-Center)..!
4] Kernel & Mesa changer To Improve Performance and compatibility..!
5] Auto-Poweroff by Timer(sos) To Shutdown OS by Timer.!
6] Many more Features to be discovered in Sos ( TO Enter SOS Press Alt+f1 Or ALt+fn+f1 And type sos , hit enter...!).

SOS v5 is based on Gearlock Core system.

What we used from Gearlock?

1] Gearlock Installer which help's to install on the system.
2] Gealock Linux environment system.
3] Gearlock Mount Filesystem.

Gearlock source code can found at:- https://github.com/axonasif/gearlock

Credits:-
1] Special Thanks To PhoenixOS & PrimeOS Team and Android X86.
2] Special Thanks To Supreme Gamers.
3] SOS Coded By Narendra,Spectre & Daksh.
4] Extreme Mode Etc...  Done By Spectre.

Copyright Notice:-

SaveOurSoul-5(SOS) is licensed under the GNU General Public License v3.0.

Thanks to all GhostXofficial Members for the Support.! 

Peace Out..! Stay Happy..!
EOT
echo -e "\e[0m"
echo -e "\e[93;1mPress Enter For Main Menu..!\e[0m"
read
bash /system/ghost/script/menu 
